### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by arvandmoe** [nilva-challenge/Android-NilvaSignal#1]
I built and ran the application but can't recover my account and I don't receive a verification code. I tried the calling method too, but it doesn't work either.

I'm contacting the signal support team to get more details regarding this issue.

Any other workarounds? please help me out.

**Comment by nilva-co** [comment]
Happy new year @Mdkhaki 
Well done running application so far. As for your question, actually we don't need the APIs working, you could drop the authentication parts and app could be used offline (for the goal is bluetooth messaging).

good luck.

**Comment by arvandmoe** [comment]
I just didn't want to break things apart.
I will do so.

Thanks for your clarification.
